services:
    nifi:
        hostname: workshop-nifi-dia1
        container_name: workshop-nifi-dia1-container 
        image: apache/nifi:2.0.0-M4
        ports:
             - "8443:8443"
        volumes:
           - nifi_conf:/opt/nifi/nifi-current/conf
           - nifi_state:/opt/nifi/nifi-current/state
           - nifi_logs:/opt/nifi/nifi-current/logs
           - nifi_database_repository:/opt/nifi/nifi-current/database_repository
           - nifi_flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
           - nifi_content_repository:/opt/nifi/nifi-current/content_repository
           - nifi_provenance_repository:/opt/nifi/nifi-current/provenance_repository
           - ./nifi/files:/opt/nifi/nifi-current/files
        environment:
            - NIFI_CLUSTER_IS_NODE=false
            - SINGLE_USER_CREDENTIALS_USERNAME=${SINGLE_USER_CREDENTIALS_USERNAME}
            - SINGLE_USER_CREDENTIALS_PASSWORD=${SINGLE_USER_CREDENTIALS_PASSWORD}
            - NIFI_JVM_HEAP_INIT=4g
            - NIFI_JVM_HEAP_MAX=8g
            - TZ=America/Sao_Paulo
volumes:
    nifi_conf:
    nifi_state:
    nifi_logs:
    nifi_database_repository:
    nifi_flowfile_repository:
    nifi_content_repository:
    nifi_provenance_repository:
